// Phase 14.0 — Regression: BookingMapper.fromDto / fromDtoList resilience to
// an unrecognised BookingDetailResponse.status wire value.
//
// WHY THIS FILE EXISTS
// ---------------------
// Flagged by mobile-security during the Phase 14.0 re-audit: neither half of
// the mapper's unknown-status contract had a test.
//
// PHASE 7.1 UPDATE — that contract was deliberately INVERTED for the status
// case. [BookingStatus.fromWire] no longer throws on an unrecognised value, so
// the row is KEPT (previously it threw, `fromDto` rethrew as [UnknownFailure],
// and `fromDtoList`'s `on Failure { continue; }` loop DROPPED the row). The
// reasoning — a silently vanished booking is invisible and unrecoverable, and
// the master could no-show a client over it — is on `BookingStatus.fromWire`.
//
// SECURITY S1 UPDATE — the first Phase 7.1 cut kept the row by relabelling it
// CONFIRMED, which fails OPEN onto the most privileged member of the enum.
// `canAddToCalendar` is the bite: it is purely local, so the "the server
// re-validates every action" defence does not cover it and an unidentifiable
// booking would land in the device calendar. The row now decodes to
// [BookingStatus.unknown] — kept, but granting nothing. The S1 group below is
// the regression guard.
//
// The resilience loop still guards every OTHER mapping failure (missing id /
// startsAt / endsAt → [ServerFailure]), which is what the last test in this
// file pins.
//
// CONSTRUCTION NOTE: `BookingDetailResponseStatusEnum` (generated by
// openapi-generator/built_value) exposes only a PRIVATE named constructor —
// the only instances reachable through its public API are the 5 known wire
// values (CONFIRMED/COMPLETED/DECLINED/CANCELLED/NOT_COMPLETED — `PENDING`
// was retired backend-side by track 24.x booking auto-confirm and dropped
// from the generated enum), which is exactly the set
// [BookingStatus.fromWire] already maps 1:1. There
// is therefore no way to round-trip an "unrecognised" status through the
// typed builder OR through `standardSerializers.deserialize` (the generated
// enum serializer itself throws before a `BookingDetailResponse` could ever
// exist with a bad status — see `booking_repository_test.dart`'s
// `getMyBookings`/`getBookingById` groups, which cover the actually-reachable
// deserialization-failure paths at the wire boundary).
//
// To exercise `BookingMapper.fromDto`'s catch block specifically, this file
// fabricates a status value via `implements BookingDetailResponseStatusEnum`
// (the generated class carries no `final`/`sealed`/`base` modifier, so an
// unrelated class may structurally implement it) rather than extending it —
// this reaches exactly the code path `fromDto` executes
// (`BookingStatus.fromWire(statusDto.name)`) without going through any wire
// deserialization at all.
//
// Pure Dart unit test: no widget tree, no network, no Dio mocks.

import 'package:beautica_api/beautica_api.dart';
import 'package:beautica_mobile/features/booking/data/booking_mapper.dart';
import 'package:beautica_mobile/features/booking/domain/booking.dart';
import 'package:beautica_mobile/features/booking/domain/booking_display_x.dart';
import 'package:beautica_mobile/features/booking/domain/booking_status.dart';
import 'package:flutter_test/flutter_test.dart';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// A [BookingDetailResponseStatusEnum]-compatible fake carrying a wire name
/// no real backend status maps to. Assignable to
/// `BookingDetailResponseBuilder.status` because Dart structural typing does
/// not require extending the class, only implementing its member surface.
class _UnrecognisedStatus implements BookingDetailResponseStatusEnum {
  const _UnrecognisedStatus([this.name = 'RESCHEDULED']);

  /// A hypothetical future backend status this build predates.
  @override
  final String name;

  @override
  String toString() => name;
}

BookingDetailResponse _validDto({
  required String id,
  BookingDetailResponseStatusEnum status =
      BookingDetailResponseStatusEnum.CONFIRMED,
}) =>
    (BookingDetailResponseBuilder()
          ..id = id
          ..masterId = 'master-1'
          ..masterServiceId = 'service-1'
          ..masterFirstName = 'Оля'
          ..masterLastName = 'Коваль'
          ..serviceName = 'Манікюр'
          ..status = status
          ..startsAt = DateTime.utc(2026, 7, 10, 10)
          ..endsAt = DateTime.utc(2026, 7, 10, 11)
          ..priceAtBooking = 500
          ..durationMinutesAtBooking = 60
          ..canReview = false
          ..masterType = BookingDetailResponseMasterTypeEnum.INDEPENDENT_MASTER)
        .build();

BookingDetailResponse _dtoWithUnrecognisedStatus(
  String id, {
  String wire = 'RESCHEDULED',
}) =>
    (BookingDetailResponseBuilder()
          ..id = id
          ..masterId = 'master-1'
          ..masterServiceId = 'service-1'
          ..masterFirstName = 'Оля'
          ..masterLastName = 'Коваль'
          ..serviceName = 'Манікюр'
          ..status = _UnrecognisedStatus(wire)
          ..startsAt = DateTime.utc(2026, 7, 10, 10)
          ..endsAt = DateTime.utc(2026, 7, 10, 11)
          ..priceAtBooking = 500
          ..durationMinutesAtBooking = 60
          ..canReview = false
          ..masterType = BookingDetailResponseMasterTypeEnum.INDEPENDENT_MASTER)
        .build();

/// A valid CONFIRMED DTO carrying the four location fields + arrival note.
/// Any of the address parameters may be left `null` to exercise a fallback
/// branch of `composeAddressBlock`.
BookingDetailResponse _dtoWithAddress({
  String id = 'booking-addr',
  String? cityLabel = 'Львів',
  String? districtLabel = 'Галицький',
  String? street = 'вулиця Городоцька',
  String? buildingNo = '15',
  String? locationNote = 'Третій поверх, код 1234',
}) {
  final builder = BookingDetailResponseBuilder()
    ..id = id
    ..masterId = 'master-1'
    ..masterServiceId = 'service-1'
    ..masterFirstName = 'Оля'
    ..masterLastName = 'Коваль'
    ..serviceName = 'Манікюр'
    ..status = BookingDetailResponseStatusEnum.CONFIRMED
    ..startsAt = DateTime.utc(2026, 7, 10, 10)
    ..endsAt = DateTime.utc(2026, 7, 10, 11)
    ..priceAtBooking = 500
    ..durationMinutesAtBooking = 60
    ..canReview = false
    ..masterType = BookingDetailResponseMasterTypeEnum.INDEPENDENT_MASTER;
  // built_value builders reject a `= null` assignment as a no-op only for
  // set fields; leaving them unset is how a null wire value is represented,
  // so assign ONLY the non-null parameters.
  if (cityLabel != null) builder.cityLabel = cityLabel;
  if (districtLabel != null) builder.districtLabel = districtLabel;
  if (street != null) builder.street = street;
  if (buildingNo != null) builder.buildingNo = buildingNo;
  if (locationNote != null) builder.locationNote = locationNote;
  return builder.build();
}

void main() {
  // ==========================================================================
  // Address-block mapping (feat/booking-auto-confirm defensive guard).
  //
  // The booking-detail "city only" address bug was a DATA problem (a seed
  // master with null street/building/note), NOT a mobile mapping bug — the DTO
  // → Booking → composeAddressBlock chain is correct. These tests PIN that
  // chain so a FUTURE mobile change that drops the finer fields (street /
  // buildingNo / districtLabel / locationNote) between the wire DTO and the
  // rendered «Адреса» block fails here, loudly, at unit level.
  //
  // Both branches are documented on purpose: the FULL address (street present)
  // and the intentional CITY-ONLY fallback (street + district absent), so the
  // test also records that the sparse-data path is by design, not a regression.
  // ==========================================================================
  group('BookingMapper.fromDto — address enrichment', () {
    test('carries every location field through to the full addressBlock '
        '(value «street, no» + detail «district район, city»)', () {
      final Booking b = BookingMapper.fromDto(_dtoWithAddress());

      // Raw fields survive the mapping unchanged.
      expect(b.street, 'вулиця Городоцька');
      expect(b.buildingNo, '15');
      expect(b.districtLabel, 'Галицький');
      expect(b.cityLabel, 'Львів');
      expect(
        b.locationNote,
        'Третій поверх, код 1234',
        reason: 'the arrival note must be preserved for «Деталі запису»',
      );

      // The composed «Деталі запису» block: precise value on top, coarse
      // locators beneath — the exact shape a future field-drop would break.
      final (String? value, String? detail) = b.addressBlock;
      expect(
        value,
        'вулиця Городоцька, 15',
        reason:
            'the full-address value must join street + building — dropping '
            'buildingNo or street silently reintroduces the city-only bug',
      );
      expect(
        detail,
        'Галицький район, Львів',
        reason:
            'the coarse detail must keep BOTH the district and the city on '
            'the detail screen (rule 1 is relaxed here by design)',
      );
    });

    test('street present but building absent → value is the bare street '
        '(a lone street is still a real address)', () {
      final Booking b = BookingMapper.fromDto(
        _dtoWithAddress(buildingNo: null),
      );

      final (String? value, String? detail) = b.addressBlock;
      expect(value, 'вулиця Городоцька');
      expect(detail, 'Галицький район, Львів');
    });

    test('street + district BOTH absent → intentional city-only fallback '
        '(«Львів», null), documenting the sparse-data branch is by design', () {
      final Booking b = BookingMapper.fromDto(
        _dtoWithAddress(street: null, buildingNo: null, districtLabel: null),
      );

      final (String? value, String? detail) = b.addressBlock;
      expect(
        value,
        'Львів',
        reason:
            'with no street and no district the city alone is the whole '
            'address — this is the intended fallback, not a regression',
      );
      expect(detail, isNull, reason: 'city-only has no coarse line beneath it');
    });

    test(
      'no location fields at all → (null, null) so the caller omits the row',
      () {
        final Booking b = BookingMapper.fromDto(
          _dtoWithAddress(
            cityLabel: null,
            districtLabel: null,
            street: null,
            buildingNo: null,
            locationNote: null,
          ),
        );

        expect(b.addressBlock, (null, null));
        expect(b.locationNote, isNull);
      },
    );
  });

  // ==========================================================================
  // The FROZEN price band. `priceMaxAtBooking` is the range CEILING the
  // backend locked in at booking time, sent ONLY when the master genuinely
  // left the service as a RANGE then. Its null is MEANINGFUL — "single price"
  // — so unlike every other nullable field the mapper defaults, it must reach
  // the domain as a null and never be coalesced to 0.0 or to the floor.
  // ==========================================================================
  group('BookingMapper.fromDto — frozen price band', () {
    test('an absent priceMaxAtBooking maps to a NULL priceMax (single '
        'price), never 0.0 and never a copy of the floor', () {
      final Booking b = BookingMapper.fromDto(_validDto(id: 'booking-fixed'));

      expect(b.price, 500);
      expect(
        b.priceMax,
        isNull,
        reason:
            'a null ceiling means SINGLE PRICE — coalescing it (to 0.0, or to '
            'priceAtBooking) erases the distinction the renderer keys off',
      );
      expect(b.priceLabel, '500 ₴');
    });

    test('a present priceMaxAtBooking maps through as the band ceiling', () {
      final BookingDetailResponse dto =
          (BookingDetailResponseBuilder()
                ..id = 'booking-range'
                ..masterId = 'master-1'
                ..masterServiceId = 'service-1'
                ..masterFirstName = 'Оля'
                ..masterLastName = 'Коваль'
                ..serviceName = 'Манікюр'
                ..status = BookingDetailResponseStatusEnum.CONFIRMED
                ..startsAt = DateTime.utc(2026, 7, 10, 10)
                ..endsAt = DateTime.utc(2026, 7, 10, 11)
                ..priceAtBooking = 300
                ..priceMaxAtBooking = 500
                ..durationMinutesAtBooking = 60
                ..canReview = false
                ..masterType =
                    BookingDetailResponseMasterTypeEnum.INDEPENDENT_MASTER)
              .build();

      final Booking b = BookingMapper.fromDto(dto);

      expect(b.price, 300);
      expect(b.priceMax, 500);
      expect(b.priceLabel, '300–500 ₴');
    });
  });

  // MO-1 — the additive `appointmentId` field: non-null when the booking is one
  // line of a multi-service visit, null for a standalone legacy booking. MO-5
  // groups «Мої записи» by this id, so a silent drop would collapse every
  // multi-service card back into N separate rows — this pins the passthrough.
  group('BookingMapper.fromDto — appointmentId (MO-1)', () {
    test('a present appointmentId maps through unchanged', () {
      final BookingDetailResponse dto =
          (BookingDetailResponseBuilder()
                ..id = 'booking-in-visit'
                ..masterId = 'master-1'
                ..masterServiceId = 'service-1'
                ..masterFirstName = 'Оля'
                ..masterLastName = 'Коваль'
                ..serviceName = 'Манікюр'
                ..status = BookingDetailResponseStatusEnum.CONFIRMED
                ..startsAt = DateTime.utc(2026, 7, 10, 10)
                ..endsAt = DateTime.utc(2026, 7, 10, 11)
                ..priceAtBooking = 500
                ..durationMinutesAtBooking = 60
                ..canReview = false
                ..appointmentId = 'appt-99'
                ..masterType =
                    BookingDetailResponseMasterTypeEnum.INDEPENDENT_MASTER)
              .build();

      final Booking b = BookingMapper.fromDto(dto);

      expect(b.appointmentId, 'appt-99');
    });

    test(
      'an absent appointmentId maps to null (standalone legacy booking)',
      () {
        // _validDto never sets appointmentId → the field is null on the wire.
        final Booking b = BookingMapper.fromDto(
          _validDto(id: 'booking-legacy'),
        );

        expect(
          b.appointmentId,
          isNull,
          reason:
              'a null appointmentId is the legacy single-service shape — MO-5 '
              'treats it as its own group of one, so it must NOT default to ""',
        );
      },
    );
  });

  // ==========================================================================
  // `clientAvatarUrl` — the booking client's photo (2026-07-24).
  //
  // `_ClientAvatarMark` (`master_booking_card.dart`) renders this straight into
  // an `Image.network`, guarded by `url != null && url.isNotEmpty && scheme ==
  // 'https'`. Two things about the mapper are therefore load-bearing, and
  // NEITHER is visible from the widget tier — a widget test builds its own
  // `Booking` and never sees the DTO:
  //
  //   1. THE PASSTHROUGH. If the mapper ever stops carrying the field, every
  //      card silently falls back to the glyph. No test goes red: the glyph is
  //      a legitimate state, so the suite reads a total feature loss as the
  //      "client has no photo" path.
  //
  //   2. NO `?? ''`. Every sibling String field in this mapper IS coalesced
  //      (`serviceId: dto.masterServiceId ?? ''`), so adding one here is the
  //      natural-looking edit — and it would be wrong. An empty string is not
  //      a URL. It survives the `isNotEmpty` clause only by accident of that
  //      clause existing (the scheme check catches it too, so the mark's own
  //      behaviour would not change today) — but it would put a bare `''` on
  //      the domain object, where "no photo" stops being expressible as null
  //      and any future consumer that only null-checks starts fetching it.
  //      This pins the deliberate un-coalesced choice.
  //
  // The third test goes through `standardSerializers` rather than the typed
  // builder, so the `@BuiltValueField(wireName: 'clientAvatarUrl')` binding is
  // pinned too: a backend rename or a regenerated client that drops the field
  // fails HERE, at unit level, instead of shipping as a blank slot.
  // ==========================================================================
  group('BookingMapper.fromDto — clientAvatarUrl', () {
    test('a present https photo URL maps through unchanged', () {
      final BookingDetailResponse dto =
          (BookingDetailResponseBuilder()
                ..id = 'booking-with-photo'
                ..masterId = 'master-1'
                ..masterServiceId = 'service-1'
                ..masterFirstName = 'Оля'
                ..masterLastName = 'Коваль'
                ..serviceName = 'Манікюр'
                ..status = BookingDetailResponseStatusEnum.CONFIRMED
                ..startsAt = DateTime.utc(2026, 7, 10, 10)
                ..endsAt = DateTime.utc(2026, 7, 10, 11)
                ..priceAtBooking = 500
                ..durationMinutesAtBooking = 60
                ..canReview = false
                ..clientAvatarUrl = 'https://cdn.example.com/avatars/c-1.png'
                ..masterType =
                    BookingDetailResponseMasterTypeEnum.INDEPENDENT_MASTER)
              .build();

      final Booking b = BookingMapper.fromDto(dto);

      expect(
        b.clientAvatarUrl,
        'https://cdn.example.com/avatars/c-1.png',
        reason:
            'the mark hands this value straight to Image.network — any '
            'rewriting, trimming or re-hosting here changes what is fetched',
      );
    });

    test('an absent photo maps to NULL — never to the empty string', () {
      // _validDto never sets clientAvatarUrl → null on the wire. This is BOTH
      // the guest/LINK booking and the registered-client-with-no-photo case;
      // the backend makes them deliberately indistinguishable.
      final Booking b = BookingMapper.fromDto(
        _validDto(id: 'booking-no-photo'),
      );

      expect(
        b.clientAvatarUrl,
        isNull,
        reason:
            'a missing photo must stay null all the way to the card, which '
            'reads null as "render the fallback glyph"',
      );
      expect(
        b.clientAvatarUrl,
        isNot(''),
        reason:
            'the deliberate NON-coalescing pin: a `?? \'\'` here would put a '
            'non-URL on the domain object and make "no photo" inexpressible '
            'as null. The card\'s https guard would still reject it, but only '
            'incidentally — this must not depend on that luck.',
      );
    });

    test('the wire name survives deserialization — a renamed or dropped '
        '`clientAvatarUrl` field fails here, not as a blank slot on the '
        'card', () {
      final BookingDetailResponse? dto = standardSerializers
          .deserializeWith(BookingDetailResponse.serializer, <String, Object?>{
            'id': 'booking-wire',
            'masterId': 'master-1',
            'masterServiceId': 'service-1',
            'masterFirstName': 'Оля',
            'masterLastName': 'Коваль',
            'masterType': 'INDEPENDENT_MASTER',
            'serviceName': 'Манікюр',
            'status': 'CONFIRMED',
            'startsAt': '2026-07-10T10:00:00Z',
            'endsAt': '2026-07-10T11:00:00Z',
            'priceAtBooking': 500,
            'durationMinutesAtBooking': 60,
            'canReview': false,
            'clientAvatarUrl': 'https://cdn.example.com/avatars/c-1.png',
          });

      expect(dto, isNotNull, reason: 'precondition: the envelope decodes');

      final Booking b = BookingMapper.fromDto(dto!);

      expect(
        b.clientAvatarUrl,
        'https://cdn.example.com/avatars/c-1.png',
        reason:
            'JSON key -> @BuiltValueField(wireName:) -> DTO -> mapper -> domain '
            'is the whole contract surface this feature added; a rename on '
            'either side must fail loudly here',
      );
    });
  });

  group('BookingStatus.fromWire', () {
    // Phase 7.1 reversed the old throw-on-unknown contract (a dropped booking
    // is invisible to the master, so the row must survive). Security S1 then
    // reversed the FALLBACK TARGET: the row survives as `unknown`, not as
    // `confirmed`. See the S1 regression group below for why that matters.
    test('decodes an unrecognised wire value as BookingStatus.unknown', () {
      expect(BookingStatus.fromWire('RESCHEDULED'), BookingStatus.unknown);
    });

    test('round-trips every FILTERABLE status through wireValue', () {
      for (final BookingStatus s in BookingStatus.filterable) {
        expect(BookingStatus.fromWire(s.wireValue), s);
      }
    });

    test('`unknown` is decode-only — it is not in `filterable`, so it can '
        'never be built into a status filter', () {
      expect(BookingStatus.filterable, isNot(contains(BookingStatus.unknown)));
      expect(
        BookingStatus.filterable.length,
        BookingStatus.values.length - 1,
        reason:
            'filterable must be every real backend status; if the backend '
            'enum grew, add the member to BOTH values and filterable',
      );
      // The backend's @Size(max = 5) cap is sized to exactly this list.
      expect(BookingStatus.filterable, hasLength(5));
    });

    test('PENDING is retired — it decodes as `unknown`, not as a distinct '
        'status and not as CONFIRMED', () {
      expect(BookingStatus.fromWire('PENDING'), BookingStatus.unknown);
    });
  });

  group('BookingMapper.fromDto — unrecognised status', () {
    test('maps to an `unknown` booking rather than throwing', () {
      final dto = _dtoWithUnrecognisedStatus('booking-bad');

      final Booking b = BookingMapper.fromDto(dto);

      expect(b.id, 'booking-bad');
      expect(b.status, BookingStatus.unknown);
    });

    // ── Security S1 regression guard ──────────────────────────────────────
    //
    // The pre-S1 code decoded an unknown status to CONFIRMED, which is the
    // most PRIVILEGED member of the enum. The documented defence was "every
    // action endpoint re-validates, so the worst case is a 409" — and that is
    // true of reschedule and cancel, but NOT of add-to-calendar, which is
    // purely local. A row the app cannot even identify would have been written
    // into the device calendar (readable by any app holding READ_CALENDAR) as
    // a live appointment. These three assertions are the guard.
    test('an EXPIRED (unrecognised) status is PRESENT in the list and grants '
        'no local capability — the S1 fail-open guard', () {
      final Booking b = BookingMapper.fromDto(
        _dtoWithUnrecognisedStatus('booking-expired', wire: 'EXPIRED'),
      );

      // 1. The row survives — this is the Phase 7.1 property, still held.
      expect(b.id, 'booking-expired');
      expect(b.status, BookingStatus.unknown);

      // 2. The capability with NO server round-trip to re-validate it.
      expect(
        b.canAddToCalendar,
        isFalse,
        reason:
            'add-to-calendar is local-only — an unidentifiable booking must '
            'never reach the device calendar',
      );

      // 3. And it asserts nothing about money either.
      expect(b.showsPrice, isFalse);
    });
  });

  group('BookingMapper.fromDtoList — resilience loop', () {
    test('KEEPS the row with an unrecognised status (mapped `unknown`) '
        'alongside the valid rows, preserving order', () {
      final dtos = <BookingDetailResponse>[
        _validDto(id: 'booking-1'),
        _dtoWithUnrecognisedStatus('booking-bad'),
        _validDto(
          id: 'booking-2',
          status: BookingDetailResponseStatusEnum.COMPLETED,
        ),
      ];

      final result = BookingMapper.fromDtoList(dtos);

      expect(result, hasLength(3));
      expect(result[0].id, 'booking-1');
      expect(result[0].status, BookingStatus.confirmed);
      // The unknown-status row survives — as `unknown`, NOT relabelled
      // CONFIRMED (security S1).
      expect(result[1].id, 'booking-bad');
      expect(result[1].status, BookingStatus.unknown);
      expect(result[2].id, 'booking-2');
      expect(result[2].status, BookingStatus.completed);
    });

    test('an all-unknown-status list maps every row to `unknown`, never '
        'throwing and never dropping', () {
      final dtos = <BookingDetailResponse>[
        _dtoWithUnrecognisedStatus('booking-bad-1'),
        _dtoWithUnrecognisedStatus('booking-bad-2'),
      ];

      final result = BookingMapper.fromDtoList(dtos);

      expect(result, hasLength(2));
      expect(
        result.map((Booking b) => b.status),
        everyElement(BookingStatus.unknown),
      );
    });

    test(
      'still drops a row with a missing required field (ServerFailure) — '
      'the resilience loop survives the Phase 7.1 status-fallback change',
      () {
        final dtos = <BookingDetailResponse>[
          _validDto(id: 'booking-1'),
          BookingDetailResponseBuilder().build(), // id left unset
        ];

        final result = BookingMapper.fromDtoList(dtos);

        expect(result, hasLength(1));
        expect(result.single.id, 'booking-1');
      },
    );
  });
}
