// Phase 14.0 — Client booking data foundation: [CreateBookingRequest].
//
// The client-side write payload for `POST /bookings`. [idempotencyKey] must
// be a fresh UUID v4 generated by the CALLER (the confirmation-screen notifier
// in Phase 14.2) once per user-initiated submit — retries of the SAME submit
// (e.g. a bounded auto-retry after a transient network error) must reuse the
// same key so the backend can de-duplicate a double-send. No UUID generator
// exists yet in `beautica-mobile` (checked before adding this field); this
// data-layer phase only defines the wire shape — key generation is deferred to
// the screen/notifier that owns the "one key per submit" invariant.
//
// Pure Dart: no Flutter imports anywhere in this file.

import 'package:freezed_annotation/freezed_annotation.dart';

part 'create_booking_request.freezed.dart';

/// Write payload for `POST /bookings`.
@freezed
abstract class CreateBookingRequest with _$CreateBookingRequest {
  const factory CreateBookingRequest({
    required String masterId,
    required String serviceId,
    required DateTime startAt,

    /// UUID v4, one per user-initiated submit. See the file header for the
    /// retry/dedupe contract.
    required String idempotencyKey,
    String? clientComment,
  }) = _CreateBookingRequest;
}
