// MO-1 — Multi-service single-visit data foundation: [CreateAppointmentRequest].
//
// The client-side write payload for `POST /appointments` — the multi-service
// analogue of `create_booking_request.dart`'s single-service
// [CreateBookingRequest]. Where the legacy flow issued N `POST /bookings` calls
// (one per selected service), a visit is ONE `POST /appointments` carrying the
// ordered [masterServiceIds] against a single master and a single [startAt];
// the backend schedules the services back-to-back from that start.
//
// [idempotencyKey] must be a fresh UUID v4 generated by the CALLER (the
// confirm-screen notifier, MO-3) once per user-initiated submit — retries of
// the SAME submit reuse the same key so the backend de-duplicates a double-send
// (same contract as [CreateBookingRequest.idempotencyKey]).
//
// [allowClientOverlap] (backend session, `CLIENT_BOOKING_CONFLICT` self-
// overlap track) — defaults `false`, matching the backend's own default.
// `true` tells the server to skip ONLY `assertNoClientConflict` (the CLIENT's
// own overlapping-booking check); the per-master `no_overlapping_bookings`
// EXCLUDE constraint is untouched and unwaivable. Set `true` for exactly ONE
// resubmit, immediately after the client explicitly confirms a
// `ClientBookingConflictFailure` dialog — never sticky, never set on the
// first attempt (see `salon_booking_confirm_screen.dart`'s `_submitOne`).
//
// NAMING COLLISION: the generated wire `CreateAppointmentRequest`
// (`beautica_api`) shares this exact class name, resolved in
// `appointment_repository.dart` via a `hide` + aliased-`show` import pair —
// mirroring the `CreateBookingRequest` precedent.
//
// Pure Dart: no Flutter imports anywhere in this file.

import 'package:freezed_annotation/freezed_annotation.dart';

part 'create_appointment_request.freezed.dart';

/// Write payload for `POST /appointments`.
@freezed
abstract class CreateAppointmentRequest with _$CreateAppointmentRequest {
  const factory CreateAppointmentRequest({
    required String masterId,

    /// The selected `MasterService.id`s, in the ORDER the services should run
    /// in the visit. Order is load-bearing — the backend schedules the items
    /// back-to-back in this sequence from [startAt].
    required List<String> masterServiceIds,

    /// The client's chosen start for the WHOLE visit (its first service).
    required DateTime startAt,

    /// UUID v4, one per user-initiated submit. See the file header for the
    /// retry/dedupe contract.
    required String idempotencyKey,
    String? clientComment,

    /// Skips the CLIENT's own overlapping-booking check when `true`. See the
    /// file header — defaults `false` (every pre-existing caller unaffected).
    @Default(false) bool allowClientOverlap,
  }) = _CreateAppointmentRequest;
}
