// Phase 2.13 — Widget tests for ResetPasswordScreen (VelvetTouch).
//
// Key changes from the pre-VelvetTouch version:
//   - All Key('snake-case') references updated to ValueKey<String>('snake_case').
//   - _lengthDotColor helper and _kDotOk/_kDotNo removed — PasswordCriteriaRow
//     (old glassmorphism widget) is no longer used. Criterion liveness is now
//     asserted via PasswordChecklist icon type (check_circle_rounded = met).
//   - 'reset-criteria-row' key removed; checklist is found via
//     find.byType(PasswordChecklist).
//   - 'reset-back-to-login' key removed — the new screen has no bottom
//     back-to-login link. Navigation back is provided by the AuthScaffold
//     back button (NeumorphicIconButton → Navigator.maybePop).
//   - 'reset-success-cta' → 'reset_back_login'.
//   - Visibility toggle keys are auto-generated by NeumorphicTextField from
//     the label string: ValueKey<String>('${label}_toggle').
//
// Covered scenarios:
//   1. PasswordChecklist present + mismatch error → submit blocked, repo NOT called.
//   2. Valid matching password → confirmPasswordReset called + success state shown.
//   3. Success CTA navigates to /login.
//   4. Invalid token (generic 400) → invalid-link state + CTA to /forgot-password.
//   5. PasswordChecklist icon flips unmet→met as password is typed.
//   6. Empty token → backend 400 drives the invalid-link state (fail-closed).
//   7. NetworkFailure → inline error, stays on form (not invalid state).
//   8. ServerFailure → inline error, stays on form.
//   9. Visibility toggles reveal/hide both password fields.

import 'dart:async';

import 'package:beautica_mobile/core/errors/failures.dart';
import 'package:beautica_mobile/core/storage/secure_storage_provider.dart';
import 'package:beautica_mobile/features/auth/data/auth_repository_provider.dart';
import 'package:beautica_mobile/features/auth/presentation/reset_password_screen.dart';
import 'package:beautica_mobile/features/auth/presentation/widgets/password_checklist.dart';
import 'package:beautica_mobile/l10n/app_localizations.dart';
import 'package:beautica_mobile/routing/route_names.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';

import '../../../helpers/fakes/fake_auth_repository.dart';
import '../../../helpers/fakes/fake_secure_storage.dart';

const String _kTicket = 'raw-reset-ticket';

GoRouter _makeRouter({
  String resetTicket = _kTicket,
  bool fromChangePassword = false,
}) => GoRouter(
  initialLocation: RouteNames.resetPassword,
  redirect: (context, state) => null,
  routes: <RouteBase>[
    GoRoute(
      path: RouteNames.resetPassword,
      builder: (context, state) => ResetPasswordScreen(
        resetTicket: resetTicket,
        fromChangePassword: fromChangePassword,
      ),
    ),
    GoRoute(
      path: RouteNames.login,
      builder: (context, state) =>
          const Scaffold(body: Center(child: Text('login'))),
    ),
    GoRoute(
      path: RouteNames.forgotPassword,
      builder: (context, state) =>
          const Scaffold(body: Center(child: Text('forgot'))),
    ),
  ],
);

Future<void> _pump(
  WidgetTester tester,
  FakeAuthRepository repo, {
  String resetTicket = _kTicket,
  bool fromChangePassword = false,
  FakeSecureStorage? storage,
}) async {
  final GoRouter router = _makeRouter(
    resetTicket: resetTicket,
    fromChangePassword: fromChangePassword,
  );
  addTearDown(router.dispose);
  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        authRepositoryProvider.overrideWith((_) => repo),
        secureStorageProvider.overrideWith(
          (_) => storage ?? FakeSecureStorage(),
        ),
      ],
      child: MaterialApp.router(
        routerConfig: router,
        localizationsDelegates: AppLocalizations.localizationsDelegates,
        supportedLocales: AppLocalizations.supportedLocales,
      ),
    ),
  );
  await tester.pumpAndSettle();
}

void main() {
  group('ResetPasswordScreen', () {
    testWidgets('1. PasswordChecklist present + mismatch blocks submit', (
      WidgetTester tester,
    ) async {
      final FakeAuthRepository repo = FakeAuthRepository();
      await _pump(tester, repo);
      final AppLocalizations l10n = AppLocalizations.of(
        tester.element(find.byKey(const ValueKey<String>('reset_password'))),
      );

      // PasswordChecklist is present in the form state.
      expect(find.byType(PasswordChecklist), findsOneWidget);

      await tester.enterText(
        find.byKey(const ValueKey<String>('reset_password')),
        'Password1',
      );
      await tester.enterText(
        find.byKey(const ValueKey<String>('reset_confirm')),
        'Different1',
      );
      await tester.tap(find.byKey(const ValueKey<String>('reset_submit')));
      await tester.pumpAndSettle();

      // Mismatch error shown; repo not called; still on the form.
      expect(find.text(l10n.errPasswordsMismatch), findsOneWidget);
      expect(repo.confirmPasswordResetCalls, isEmpty);
      expect(
        find.byKey(const ValueKey<String>('reset_password')),
        findsOneWidget,
      );
    });

    testWidgets(
      '2. valid matching password → confirmPasswordReset called + success',
      (WidgetTester tester) async {
        final FakeAuthRepository repo = FakeAuthRepository();
        await _pump(tester, repo);

        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_password')),
          'Password1',
        );
        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_confirm')),
          'Password1',
        );
        await tester.tap(find.byKey(const ValueKey<String>('reset_submit')));
        await tester.pumpAndSettle();

        expect(repo.confirmPasswordResetCalls.length, 1);
        expect(repo.confirmPasswordResetCalls.first.resetTicket, _kTicket);
        expect(repo.confirmPasswordResetCalls.first.newPassword, 'Password1');

        // Success state — "Увійти" CTA present, form gone.
        expect(
          find.byKey(const ValueKey<String>('reset_back_login')),
          findsOneWidget,
        );
        expect(
          find.byKey(const ValueKey<String>('reset_password')),
          findsNothing,
        );
      },
    );

    testWidgets('3. success CTA navigates to /login', (
      WidgetTester tester,
    ) async {
      final FakeAuthRepository repo = FakeAuthRepository();
      await _pump(tester, repo);

      await tester.enterText(
        find.byKey(const ValueKey<String>('reset_password')),
        'Password1',
      );
      await tester.enterText(
        find.byKey(const ValueKey<String>('reset_confirm')),
        'Password1',
      );
      await tester.tap(find.byKey(const ValueKey<String>('reset_submit')));
      await tester.pumpAndSettle();

      await tester.tap(find.byKey(const ValueKey<String>('reset_back_login')));
      await tester.pumpAndSettle();

      expect(find.text('login'), findsOneWidget);
    });

    testWidgets(
      '4. invalid token (generic 400) → invalid state + CTA to /forgot-password',
      (WidgetTester tester) async {
        final FakeAuthRepository repo = FakeAuthRepository()
          ..confirmPasswordResetResult = const ResetTokenInvalidFailure();
        await _pump(tester, repo);

        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_password')),
          'Password1',
        );
        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_confirm')),
          'Password1',
        );
        await tester.tap(find.byKey(const ValueKey<String>('reset_submit')));
        await tester.pumpAndSettle();

        // Invalid-link state — recovery CTA present.
        expect(
          find.byKey(const ValueKey<String>('reset_invalid_cta')),
          findsOneWidget,
        );

        await tester.tap(
          find.byKey(const ValueKey<String>('reset_invalid_cta')),
        );
        await tester.pumpAndSettle();
        expect(find.text('forgot'), findsOneWidget);
      },
    );

    // MEDIUM — PasswordChecklist reactivity. Typing a PARTIAL password (4 chars,
    // no digit, no uppercase) leaves all icons as radio_button_unchecked (unmet);
    // completing it to 8+ chars must flip the length icon to check_circle_rounded.
    // Exercises the onChanged → setState(_passwordValue) chain.
    testWidgets(
      '5. PasswordChecklist icon flips unmet→met as password is typed',
      (WidgetTester tester) async {
        final FakeAuthRepository repo = FakeAuthRepository();
        await _pump(tester, repo);

        // Empty → all icons are radio_button_unchecked (unmet).
        expect(find.byIcon(Icons.radio_button_unchecked), findsWidgets);
        expect(find.byIcon(Icons.check_circle_rounded), findsNothing);

        // Partial (4 chars, lowercase only) → still all unmet.
        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_password')),
          'pass',
        );
        await tester.pump();
        expect(find.byIcon(Icons.check_circle_rounded), findsNothing);

        // 8+ chars → at least the length rule flips to met.
        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_password')),
          'password',
        );
        await tester.pump();
        // The length rule (≥8 chars) is now met — its icon is check_circle_rounded.
        expect(find.byIcon(Icons.check_circle_rounded), findsOneWidget);
      },
    );

    // MEDIUM — empty-token fail-closed. The router parses a missing `?token=`
    // to '' (empty string), and the screen still renders the form. Submitting
    // a valid new password must rely on the backend rejecting the empty token
    // with a generic 400 → ResetTokenInvalidFailure → invalid-link state.
    testWidgets('6. empty token → backend 400 drives the invalid-link state', (
      WidgetTester tester,
    ) async {
      final FakeAuthRepository repo = FakeAuthRepository()
        ..confirmPasswordResetResult = const ResetTokenInvalidFailure();
      await _pump(tester, repo, resetTicket: '');

      await tester.enterText(
        find.byKey(const ValueKey<String>('reset_password')),
        'Password1',
      );
      await tester.enterText(
        find.byKey(const ValueKey<String>('reset_confirm')),
        'Password1',
      );
      await tester.tap(find.byKey(const ValueKey<String>('reset_submit')));
      await tester.pumpAndSettle();

      // The empty token was forwarded verbatim (no client-side guess/skip).
      expect(repo.confirmPasswordResetCalls.length, 1);
      expect(repo.confirmPasswordResetCalls.first.resetTicket, '');
      // Fail-closed: invalid-link state, NOT success.
      expect(
        find.byKey(const ValueKey<String>('reset_invalid_cta')),
        findsOneWidget,
      );
      expect(
        find.byKey(const ValueKey<String>('reset_back_login')),
        findsNothing,
      );
    });

    // MEDIUM — retryable-error branch (distinct from the invalid-token path).
    // A NetworkFailure (NOT ResetTokenInvalidFailure) must show an inline error
    // and KEEP the user on the form so they can retry.
    testWidgets(
      '7. NetworkFailure → inline error, stays on form (not invalid state)',
      (WidgetTester tester) async {
        final FakeAuthRepository repo = FakeAuthRepository()
          ..confirmPasswordResetResult = const NetworkFailure();
        await _pump(tester, repo);
        final AppLocalizations l10n = AppLocalizations.of(
          tester.element(find.byKey(const ValueKey<String>('reset_password'))),
        );

        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_password')),
          'Password1',
        );
        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_confirm')),
          'Password1',
        );
        await tester.tap(find.byKey(const ValueKey<String>('reset_submit')));
        await tester.pumpAndSettle();

        expect(repo.confirmPasswordResetCalls.length, 1);
        // Inline retryable error, form still present, NOT the invalid-link card.
        expect(find.text(l10n.errNetwork), findsOneWidget);
        expect(
          find.byKey(const ValueKey<String>('reset_password')),
          findsOneWidget,
        );
        expect(
          find.byKey(const ValueKey<String>('reset_invalid_cta')),
          findsNothing,
        );
        expect(
          find.byKey(const ValueKey<String>('reset_back_login')),
          findsNothing,
        );
      },
    );

    // MEDIUM — ServerFailure shares the retryable branch with NetworkFailure.
    testWidgets('8. ServerFailure → inline error, stays on form', (
      WidgetTester tester,
    ) async {
      final FakeAuthRepository repo = FakeAuthRepository()
        ..confirmPasswordResetResult = const ServerFailure(statusCode: 503);
      await _pump(tester, repo);
      final AppLocalizations l10n = AppLocalizations.of(
        tester.element(find.byKey(const ValueKey<String>('reset_password'))),
      );

      await tester.enterText(
        find.byKey(const ValueKey<String>('reset_password')),
        'Password1',
      );
      await tester.enterText(
        find.byKey(const ValueKey<String>('reset_confirm')),
        'Password1',
      );
      await tester.tap(find.byKey(const ValueKey<String>('reset_submit')));
      await tester.pumpAndSettle();

      expect(find.text(l10n.errServer), findsOneWidget);
      expect(
        find.byKey(const ValueKey<String>('reset_password')),
        findsOneWidget,
      );
      expect(
        find.byKey(const ValueKey<String>('reset_invalid_cta')),
        findsNothing,
      );
    });

    // LOW — password-visibility toggles flip obscureText on both fields.
    // Stable const Keys ('reset_password_toggle' / 'reset_confirm_toggle') are
    // passed via NeumorphicTextField.toggleKey — no locale-coupling required.
    testWidgets('9. visibility toggles reveal/hide both password fields', (
      WidgetTester tester,
    ) async {
      final FakeAuthRepository repo = FakeAuthRepository();
      await _pump(tester, repo);

      // Stable locale-independent keys set via NeumorphicTextField.toggleKey.
      const Key newToggleKey = Key('reset_password_toggle');
      const Key confirmToggleKey = Key('reset_confirm_toggle');

      EditableText editableUnder(Key fieldKey) => tester.widget<EditableText>(
        find.descendant(
          of: find.byKey(fieldKey),
          matching: find.byType(EditableText),
        ),
      );

      // Both start obscured.
      expect(
        editableUnder(const ValueKey<String>('reset_password')).obscureText,
        isTrue,
      );
      expect(
        editableUnder(const ValueKey<String>('reset_confirm')).obscureText,
        isTrue,
      );

      // Ensure both toggles are in the viewport before tapping
      // (AuthScaffold body is scrollable; confirm field may be below fold).
      await tester.ensureVisible(find.byKey(newToggleKey));
      await tester.tap(find.byKey(newToggleKey));
      await tester.pump();
      await tester.ensureVisible(find.byKey(confirmToggleKey));
      await tester.tap(find.byKey(confirmToggleKey));
      await tester.pump();

      // Both revealed after toggling.
      expect(
        editableUnder(const ValueKey<String>('reset_password')).obscureText,
        isFalse,
      );
      expect(
        editableUnder(const ValueKey<String>('reset_confirm')).obscureText,
        isFalse,
      );
    });

    // -------------------------------------------------------------------------
    // Beautica OTP task Phase B5 — fromChangePassword forced-logout branch.
    // -------------------------------------------------------------------------

    testWidgets(
      '10. fromChangePassword: true → success logs out, shows forced-logout '
      'message, and navigates to /login (skips the normal success state)',
      (WidgetTester tester) async {
        final FakeAuthRepository repo = FakeAuthRepository();
        final FakeSecureStorage storage = FakeSecureStorage();
        // Seed a refresh token as if the user was already logged in — the
        // forced logout must wipe it just like an explicit logout would.
        await storage.writeRefreshToken('session-refresh-token');

        await _pump(tester, repo, fromChangePassword: true, storage: storage);
        // Capture l10n from the widget tree's ACTUAL resolved locale (matches
        // the pattern used by every other test in this file) while the field
        // is still present — it is gone once the forced-logout flow submits.
        final AppLocalizations l10n = AppLocalizations.of(
          tester.element(find.byKey(const ValueKey<String>('reset_password'))),
        );

        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_password')),
          'Password1',
        );
        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_confirm')),
          'Password1',
        );
        await tester.tap(find.byKey(const ValueKey<String>('reset_submit')));
        // Deliberately NOT pumpAndSettle() yet — the SnackBar auto-dismisses
        // on its own timer, and pumpAndSettle() pumps straight past that,
        // leaving nothing to assert against. A few bounded pumps let the
        // async confirmPasswordReset → logout → snackbar → context.go chain
        // settle while the SnackBar is still on screen.
        await tester.pump(); // begin async confirmPasswordReset
        await tester.pump(); // microtasks (logout, storage wipe)
        // fixed-wait-ok: real-async step — SnackBar must still be visible below (see comment above).
        await tester.pump(const Duration(milliseconds: 50));

        // confirmPasswordReset was called with the ticket + new password.
        expect(repo.confirmPasswordResetCalls.length, 1);
        expect(repo.confirmPasswordResetCalls.first.resetTicket, _kTicket);

        // Logout ran (best-effort server call + local wipe) and the refresh
        // token is gone from storage.
        expect(repo.logoutCallCount, 1);
        expect(await storage.readRefreshToken(), isNull);

        // Skips the normal in-screen success state entirely.
        expect(
          find.byKey(const ValueKey<String>('reset_back_login')),
          findsNothing,
        );

        // Lands on /login with the forced-logout snackbar message still visible.
        expect(find.text('login'), findsOneWidget);
        expect(
          find.text(l10n.changePasswordForcedLogoutMessage),
          findsOneWidget,
        );

        // Let the SnackBar's own timer finish so no pending timers leak past
        // the test.
        await tester.pumpAndSettle();
      },
    );

    testWidgets(
      '11. fromChangePassword: false (default) → success shows the normal '
      'in-screen success state, NOT the forced-logout flow',
      (WidgetTester tester) async {
        final FakeAuthRepository repo = FakeAuthRepository();
        await _pump(tester, repo);

        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_password')),
          'Password1',
        );
        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_confirm')),
          'Password1',
        );
        await tester.tap(find.byKey(const ValueKey<String>('reset_submit')));
        await tester.pumpAndSettle();

        // logout() must NOT be called on the plain forgot-password path.
        expect(repo.logoutCallCount, 0);
        expect(
          find.byKey(const ValueKey<String>('reset_back_login')),
          findsOneWidget,
        );
        expect(find.text('login'), findsNothing);
      },
    );

    // mobile-security MEDIUM fix follow-up — the forced-logout branch used to
    // check `if (!mounted) return;` BEFORE calling `logout()`, so a widget
    // disposal mid-flight (backgrounded app, swipe-back, slow network) between
    // confirmPasswordReset() resolving and that check silently skipped the
    // logout entirely: the local refresh token survived a server-side
    // revocation and the in-app session stayed Authenticated. The fix
    // captures the AuthNotifier synchronously before the first await and
    // calls logout() unconditionally, gating only the UI-facing effects
    // (SnackBar / context.go) on `mounted`. This test asserts the CORRECT
    // (post-fix) behaviour directly against the repository/storage rather
    // than the UI, since the widget is deliberately disposed before the
    // assertions run.
    testWidgets(
      '12. fromChangePassword: true — logout() still runs (and the refresh '
      'token is still wiped) even when the widget is disposed while '
      'confirmPasswordReset is in flight',
      (WidgetTester tester) async {
        final Completer<void> completer = Completer<void>();
        final FakeAuthRepository repo = FakeAuthRepository()
          ..confirmPasswordResetDelay = completer.future;
        final FakeSecureStorage storage = FakeSecureStorage();
        await storage.writeRefreshToken('session-refresh-token');

        final GoRouter router = _makeRouter(fromChangePassword: true);
        addTearDown(router.dispose);
        await tester.pumpWidget(
          ProviderScope(
            overrides: [
              authRepositoryProvider.overrideWith((_) => repo),
              secureStorageProvider.overrideWith((_) => storage),
            ],
            child: MaterialApp.router(
              routerConfig: router,
              localizationsDelegates: AppLocalizations.localizationsDelegates,
              supportedLocales: AppLocalizations.supportedLocales,
            ),
          ),
        );
        await tester.pumpAndSettle();

        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_password')),
          'Password1',
        );
        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_confirm')),
          'Password1',
        );
        await tester.tap(find.byKey(const ValueKey<String>('reset_submit')));
        // Start confirmPasswordReset(); it suspends on the completer, so
        // ResetPasswordScreen is still on-screen and _submitting == true.
        await tester.pump();

        // Simulate the widget disposing mid-flight — navigate away BEFORE
        // confirmPasswordReset resolves so ResetPasswordScreen is unmounted
        // while the request is still pending.
        router.go(RouteNames.login);
        await tester.pumpAndSettle();
        expect(find.text('login'), findsOneWidget);

        // Now resolve the pending confirmPasswordReset call.
        completer.complete();
        await tester.pumpAndSettle();

        // confirmPasswordReset ran, and the forced-logout MUST have run
        // unconditionally even though the widget was already disposed by the
        // time it settled.
        expect(repo.confirmPasswordResetCalls.length, 1);
        expect(repo.logoutCallCount, 1);
        expect(await storage.readRefreshToken(), isNull);
      },
    );
  });

  // ---------------------------------------------------------------------------
  // GROUP 1 — passwordRules predicate boundaries
  // ---------------------------------------------------------------------------
  //
  // These tests exercise the predicates returned by passwordRules(l10n) in
  // password_checklist.dart directly via PasswordRule.test(value). They do not
  // pump a widget tree — they are pure-Dart unit tests.
  group('passwordRules predicates', () {
    late AppLocalizations l10n;

    setUpAll(() {
      // lookupAppLocalizations requires a Locale — use UK (primary).
      l10n = lookupAppLocalizations(const Locale('uk'));
    });

    test('1. length boundary: 7 chars fails, 8 chars passes', () {
      final rules = passwordRules(l10n);
      // Rule index 0 is the length rule (≥8 chars by default).
      final lengthRule = rules[0];
      expect(
        lengthRule.test('Abcdef1'), // 7 chars
        isFalse,
        reason: '7-char value must fail the length-≥8 predicate',
      );
      expect(
        lengthRule.test('Abcdef12'), // 8 chars
        isTrue,
        reason: '8-char value must pass the length-≥8 predicate',
      );
    });

    test('2. digit rule: absent → fails, present → passes', () {
      final rules = passwordRules(l10n);
      // Rule index 1 is the digit rule.
      final digitRule = rules[1];
      expect(
        digitRule.test('Abcdefgh'), // no digit
        isFalse,
        reason: '"Abcdefgh" contains no digit — predicate must fail',
      );
      expect(
        digitRule.test('Abcdefg1'), // has digit
        isTrue,
        reason: '"Abcdefg1" contains a digit — predicate must pass',
      );
    });

    test('3. Latin uppercase rule: absent → fails, present → passes', () {
      final rules = passwordRules(l10n);
      // Rule index 2 is the uppercase rule (covers [A-Z] and [А-ЯІЇЄ]).
      final upperRule = rules[2];
      expect(
        upperRule.test('abcdefg1'), // no uppercase
        isFalse,
        reason: '"abcdefg1" has no uppercase letter — predicate must fail',
      );
      expect(
        upperRule.test('Abcdefg1'), // has Latin uppercase
        isTrue,
        reason: '"Abcdefg1" has Latin uppercase "A" — predicate must pass',
      );
    });

    test('4. Cyrillic uppercase rule: absent → fails, present → passes', () {
      final rules = passwordRules(l10n);
      final upperRule = rules[2];
      expect(
        upperRule.test('пароль12'), // all Cyrillic lowercase + digits
        isFalse,
        reason: '"пароль12" has no uppercase — predicate must fail',
      );
      expect(
        upperRule.test('Пароль12'), // Cyrillic uppercase П
        isTrue,
        reason:
            '"Пароль12" has Cyrillic uppercase "П" (in [А-ЯІЇЄ]) — '
            'predicate must pass',
      );
    });
  });

  // ---------------------------------------------------------------------------
  // GROUP 2 — ResetPasswordScreen loading state (independent assertion)
  // ---------------------------------------------------------------------------
  group('ResetPasswordScreen loading state', () {
    testWidgets(
      '10. loading indicator visible mid-submit; normal state after complete',
      (WidgetTester tester) async {
        // A Completer that keeps the confirmPasswordReset Future pending so we
        // can assert the intermediate loading state before it resolves.
        final Completer<void> completer = Completer<void>();
        final FakeAuthRepository repo = FakeAuthRepository()
          ..confirmPasswordResetDelay = completer.future;

        await _pump(tester, repo);

        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_password')),
          'Password1',
        );
        await tester.enterText(
          find.byKey(const ValueKey<String>('reset_confirm')),
          'Password1',
        );

        // Tap submit and pump one frame — completer not yet completed, so the
        // screen stays in the loading state.
        await tester.tap(find.byKey(const ValueKey<String>('reset_submit')));
        await tester.pump();

        // The submit button must be in its loading state (loading: true on
        // NeumorphicButton renders a CircularProgressIndicator).
        expect(
          find.byType(CircularProgressIndicator),
          findsOneWidget,
          reason:
              'Mid-submit: NeumorphicButton with loading:true must show a '
              'CircularProgressIndicator',
        );

        // Resolve the completer and let the screen transition to success.
        completer.complete();
        await tester.pumpAndSettle();

        // Normal (success) state — spinner gone, success CTA present.
        expect(find.byType(CircularProgressIndicator), findsNothing);
        expect(
          find.byKey(const ValueKey<String>('reset_back_login')),
          findsOneWidget,
        );
      },
    );
  });
}
